name: repo_generator
description: Repository class code generation.
version: 0.0.5
homepage: https://github.com/SunnatilloShavkatov/repo_generator.git

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  build: any
  source_gen: ^1.3.2
  repo_annotation: ^0.0.1

dev_dependencies:
  build_test: ^2.1.7
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
