name: repo_generator
description: Repository class code generation.
version: 0.0.1
homepage: https://github.com/SunnatilloShavkatov/repo_generator.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  build: ">=2.0.0 <3.0.0"
  analyzer: ">=4.0.0 <5.0.0"
  source_gen: ">=1.0.0 <2.0.0"
  repo_annotation: ^0.0.1

dev_dependencies:
  build_test: ^2.1.5
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter

